[package]
name = "well-actually-bot"
version = "0.1.0"
authors = ["Michael Scherer <misc@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irc-bot = "0.2.1"
